export { createLogger, setLogLevel } from './logger.js';
export type { Logger, LogLevel } from './logger.js';

export {
  registry,
  executionTotal,
  executionLatency,
  executionPending,
  executionVolume,
  routeSuccessRate,
  routeSlippage,
  venueLatency,
  venueHealth,
  venueErrorRate,
  relayerStatus,
  relayerInventory,
  relayerActiveJobs,
  relayerLatency,
  marketHealthScore,
  marketLiquidity,
  syntheticExposure,
  syntheticUtilization,
  syntheticBackingRatio,
  activeAlerts,
  protocolPaused,
  circuitBreakerLevel,
  // Relayer Engine Metrics
  relayerJobsReceived,
  relayerJobsFailed,
  relayerJobsCompleted,
  relayerExecutionLatency,
  venueSubmissionLatency,
  inventoryAvailableBalance,
  inventoryReservedBalance,
  staleQuoteRejections,
  partialFillTotal,
  reconciliationMismatch,
  hedgeResidualExposure,
  relayerQueueDepth,
  riskBudgetUsed,
  // Escrow Metrics
  escrowIntentsCreated,
  escrowIntentsCompleted,
  escrowIntentsFailed,
  escrowIntentsRefunded,
  escrowIntentsExpired,
  escrowPartialFills,
  escrowActiveIntents,
  escrowLockedVolume,
  escrowSettlementLatency,
  escrowRefundVolume,
  escrowTimeoutRate,
  escrowRelayerConfirmations,
} from './prometheus.js';
