import type { TokenInfo } from '@/types';

// ── Supported Tokens ───────────────────────────────────────────────────

export const TOKENS: Record<string, TokenInfo> = {
  DCC: {
    id: 'dcc',
    symbol: 'DCC',
    name: 'DecentralChain',
    decimals: 9,
    chain: 'dcc',
    isSynthetic: false,
  },
  DUSD: {
    id: 'ACmPEtWQLQnZJcvZD7BWrnc4EySyu2kYFzEF8YFRcH9q',
    symbol: 'DUSD',
    name: 'DUSD Stablecoin',
    decimals: 6,
    chain: 'dcc',
    isSynthetic: false,
  },
  USDC: {
    id: 'usdc',
    symbol: 'USDC',
    name: 'USD Coin',
    decimals: 6,
    chain: 'dcc',
    isSynthetic: false,
  },
  SOL: {
    id: 'sol',
    symbol: 'SOL',
    name: 'Solana',
    decimals: 9,
    chain: 'solana',
    isSynthetic: false,
  },
  ETH: {
    id: 'eth',
    symbol: 'ETH',
    name: 'Ethereum',
    decimals: 18,
    chain: 'ethereum',
    isSynthetic: false,
  },
  sSOL: {
    id: 'ssol',
    symbol: 'sSOL',
    name: 'Synthetic SOL',
    decimals: 9,
    chain: 'dcc',
    isSynthetic: true,
  },
  sETH: {
    id: 'seth',
    symbol: 'sETH',
    name: 'Synthetic ETH',
    decimals: 18,
    chain: 'dcc',
    isSynthetic: true,
  },
  sBTC: {
    id: 'sbtc',
    symbol: 'sBTC',
    name: 'Synthetic BTC',
    decimals: 8,
    chain: 'dcc',
    isSynthetic: true,
  },
  sXRP: {
    id: 'sxrp',
    symbol: 'sXRP',
    name: 'Synthetic XRP',
    decimals: 8,
    chain: 'dcc',
    isSynthetic: true,
  },
  sDOGE: {
    id: 'sdoge',
    symbol: 'sDOGE',
    name: 'Synthetic DOGE',
    decimals: 8,
    chain: 'dcc',
    isSynthetic: true,
  },
  sBNB: {
    id: 'sbnb',
    symbol: 'sBNB',
    name: 'Synthetic BNB',
    decimals: 8,
    chain: 'dcc',
    isSynthetic: true,
  },
  sADA: {
    id: 'sada',
    symbol: 'sADA',
    name: 'Synthetic ADA',
    decimals: 8,
    chain: 'dcc',
    isSynthetic: true,
  },
  sAVAX: {
    id: 'savax',
    symbol: 'sAVAX',
    name: 'Synthetic AVAX',
    decimals: 8,
    chain: 'dcc',
    isSynthetic: true,
  },
  sLINK: {
    id: 'slink',
    symbol: 'sLINK',
    name: 'Synthetic LINK',
    decimals: 8,
    chain: 'dcc',
    isSynthetic: true,
  },
  sDOT: {
    id: 'sdot',
    symbol: 'sDOT',
    name: 'Synthetic DOT',
    decimals: 8,
    chain: 'dcc',
    isSynthetic: true,
  },
};
